"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.Layout = void 0;
const head_1 = __importDefault(require("next/head"));
const react_1 = __importDefault(require("react"));
const Header_1 = require("./Header");
const Footer_1 = require("./Footer");
const Layout = ({ children, dataCategories }) => {
    return (<>
            <head_1.default>
                <title>Home</title>
                <meta name="description" content="Generated by Home"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </head_1.default>

            <Header_1.Header dataCategories={dataCategories}/>
            <main className="md:mt-0 mt-16">{children}</main>
            <Footer_1.Footer />
        </>);
};
exports.Layout = Layout;
